# Generated by Django 4.2.7 on 2023-11-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
